---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: default
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
