apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 30m
  path: .
  prune: true
  timeout: 10m 
  sourceRef:
    kind: GitRepository
    name: flux-system
