apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-ebs-csi-driver
  namespace: default
spec:
  interval: 30m
  path: ./aws-ebs-csi
  prune: true
  timeout: 10m 
  sourceRef:
    kind: GitRepository
    name: default
