apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: velero
  values:
    configuration:
      backupStorageLocation:
      - bucket: kavya-backup
        provider: aws
      volumeSnapshotLocation:
      - config:
          region: ap-south-1
        provider: aws
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.7.1
      volumeMounts:
      - mountPath: /target
        name: plugins
    credentials:
      useSecret: false
    serviceAccount:
      server:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::975050086565:role/velero-backup
    schedules:
      every-minute-backup:
        disabled: false
        schedule: "* * * * *"
        paused: false
        template:
          includedNamespaces:
          - '*'
          includedResources:
          - persistentvolumes
          ttl: "24h"
          storageLocation: default
          orLabelSelectors:
            - matchLabels:
                statefulset.kubernetes.io/pod-name: dev-mongodb-dev-0
            - matchLabels:
                statefulset.kubernetes.io/pod-name: staging-mongodb-staging-1
          # hooks:
          #   resources: 
          #   name: my-hook
          #   includedNamespaces:
          #   - '*'
          #   includedResources:
          #   - pods
          #   orLabelSelectors:
          #   - matchLabels:
          #       statefulset.kubernetes.io/pod-name: dev-mongodb-dev-0
          #   - matchLabels:
          #       statefulset.kubernetes.io/pod-name: staging-mongodb-staging-1
            # pre:
            # -
            # exec:
            # container: mongodb
            # command:
            # - /bin/uname
            # - mongosh








          # labelSelector:
          #   matchLabels:
          #     statefulset.kubernetes.io/pod-name: dev-mongodb-dev-0
            

             


          
              # statefulset.kubernetes.io/pod-name: mongodb-2
                  # statefulset.kubernetes.io/pod-name=default-mysql-dev-secondary-0
          # daily-backup:
          #   disabled: false
          #   schedule: "* * * * *"
          #   paused: false
          #   template:
          #     ttl: "504h"
          #     storageLocation: kavya-backup
          #     labelSelector:
          #       matchLabels:
          #         statefulset.kubernetes.io/pod-name: mongodb-1
          #         # apps.kubernetes.io/pod-index: 1 (use this tag or above one)
          #         statefulset.kubernetes.io/pod-name=default-mysql-dev-secondary-0
            
