apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
        
  interval: 15m
  timeout: 5m
  releaseName: velero
  values:
    configuration:
      backupStorageLocation:
      - bucket: <BUCKET_NAME>
        provider: aws
      volumeSnapshotLocation:
      - config:
          region: ap-south-1
        provider: aws
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.7.1
      volumeMounts:
      - mountPath: /target
        name: plugins
    credentials:
      useSecret: false
    serviceAccount:
      server:
        annotations:
          eks.amazonaws.com/role-arn: <EKS_RECOVERY_VELERO_ROLE>
        schedules:
          hourly-backup:
            disabled: false
            schedule: "0 * * * *"
            paused: false
            template:
              ttl: "24h"
              storageLocation: <BUCKET_NAME>
              labelSelector:
                matchLabels:
                  statefulset.kubernetes.io/pod-name: mongodb-1
                  # apps.kubernetes.io/pod-index: 1 (use this tag or above one)
          daily-backup:
            disabled: false
            schedule: "0 0 * * *"
            paused: false
            template:
              ttl: "504h"
              storageLocation: <BUCKET_NAME>
              labelSelector:
                matchLabels:
                  statefulset.kubernetes.io/pod-name: mongodb-1
                  # apps.kubernetes.io/pod-index: 1 (use this tag or above one)
            
