apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: velero
  namespace: default
spec:
  interval: 30m
  path: ./velero
  prune: true
  timeout: 10m 
  sourceRef:
    kind: GitRepository
    name: default
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: velero
      namespace: velero