apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: velero
  namespace: velero
spec:
  interval: 30m
  path: .
  prune: true
  timeout: 10m 
  sourceRef:
    kind: GitRepository
    name: flux-system
