apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mongodb
  namespace: flux-system
spec:
  # type: oci
  interval: 5m0s
  url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami