---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: dev
spec:
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1m0s
  releaseName: mymongodb
  targetNamespace: dev
  values:
    architecture: replicaset
    arbiter:
      enabled: false
    replicaCount: 3
    podAnnotations:
      pre.hook.backup.velero.io/container: mongodb
      pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "mongosh --eval \"db.fsyncLock()\" -u root -p $MONGODB_ROOT_PASSWORD"]'
      post.hook.backup.velero.io/container: mongodb
      post.hook.backup.velero.io/command: '["/bin/bash", "-c", "mongosh --eval \"db.fsyncUnlock()\" -u root -p $MONGODB_ROOT_PASSWORD"]'
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
              
