apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 30m
  path: ./
  prune: true
  timeout: 10m 
  sourceRef:
    kind: Helmrelease
    name: flux-system
