apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 30m
  path: cluster/eks/mongodb
  prune: true
  timeout: 10m 
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mongodb
      namespace: 