apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql-dev
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: mysql
      version: "11.0.0"
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: flux-system
  targetNamespace: default
  values:
    image: 
      tag: 8.0.35
    # primary:
    #   nodeSelector:
    #     karpenter.sh/nodepool: db
    architecture: replication
    secondary: 
      replicaCount: 2
      podAnnotations:
        pre.hook.backup.velero.io/container: mysql
        pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "mysql -u root -pCbQb6RDDw7"]'
    #   post.hook.backup.velero.io/container: mongodb
    #   post.hook.backup.velero.io/command: '["/bin/bash", "-c", "mongosh --eval \"db.fsyncUnlock()\" -u root -p $MONGODB_ROOT_PASSWORD"]'
    # spec:
    #   containers:
    #   - name: mysql
    #     image: 
    #     env:
    #     - name: MYSQL_ROOT_PASSWORD
    #       valueFrom:
    #         secretKeyRef:
    #           name: 
    #           key: mysql-root-password
    