apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql-dev
  namespace: dev
spec:
  interval: 1m
  chart:
    spec:
      chart: mysql
      version: "11.0.0"
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: flux-system
  values:
    image: 
      tag: 8.0.35
    primary:
      nodeSelector:
        karpenter.sh/nodepool: db