apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: example-kustomization
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-eks/clusters/eks
    namespace: flux-eks/clusters/eks
