---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  chart:
    spec:
      chart: velero
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
  interval: 1m0s
  releaseName: velero
  targetNamespace: velero
  valuesFrom:
  - configMapKeyRef:
      name: velero-configmap
      key: velero_values.yaml
