apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-default-mysql-dev-primary-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 8Gi
  volumeName: pvc-54448967-ff86-456c-b26a-343c1e7f19de
