apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-default-mysql-dev-primary-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 8Gi
  volumeName: pvc-e9b15763-dd79-4c2f-8884-569016283673
