apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-default-mysql-dev-secondary-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 8Gi
  volumeName: pvc-62cbf954-6c9c-44fc-82b4-9a0926854588
